-- 聯絡我們表單資料表
CREATE TABLE IF NOT EXISTS `contact_inquiry` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(100) NOT NULL COMMENT '姓名',
  `email` VARCHAR(255) NOT NULL COMMENT '信箱',
  `phone` VARCHAR(20) DEFAULT NULL COMMENT '手機號碼',
  `address` VARCHAR(500) DEFAULT NULL COMMENT '地址',
  `content` TEXT NOT NULL COMMENT '問題內容',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '建立時間'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='聯絡我們表單';
